export interface FileObject {
  id: string;
  name: string;
  type: 'pdf' | 'sheet';
  content: string; // This will be fetched from the mock Google Drive service
  summary: string; // This will be generated by Gemini
  status: 'idle' | 'indexing' | 'indexed' | 'error' | 'syncing'; // Added 'syncing'
}

export interface Client {
  id: string;
  name: string;
  files: FileObject[]; // This will represent the state of files as known by our app (and synced to File Search)
  apiKey: string;
  googleDriveFolderUrl: string | null; // New field
}
